#main{
	margin-left:350px;
	width:700px;
	height:720px;
	border:#CCC ridge 1px;
	background:#2C7294;
}

#sub{	
	margin-left:60px;
}

#menu{
	margin-left:60px;
	margin-top:30px;
	padding:5px 5px 5px 5px;
	width:550px;
	height:200px;
	border:#FFF ridge 2px;
	color:#FFF;	
}

#footer p{
		margin-top:100px;
		padding-top:5px;
		background:#590D0F;
		color:#FFF;
		height:30px;
		text-align:center;
}

#footer a{
	text-decoration:none;	
}
